/// Generated by AssetsRefGenerator on 2021/06/06
class Res {
  static const String Roboto_Black = "assets/fonts/Roboto_Black.ttf";
  static const String Roboto_BlackItalic = "assets/fonts/Roboto_BlackItalic.ttf";
  static const String Roboto_Bold = "assets/fonts/Roboto_Bold.ttf";
  static const String Roboto_BoldItalic = "assets/fonts/Roboto_BoldItalic.ttf";
  static const String Roboto_Italic = "assets/fonts/Roboto_Italic.ttf";
  static const String Roboto_Light = "assets/fonts/Roboto_Light.ttf";
  static const String Roboto_LightItalic = "assets/fonts/Roboto_LightItalic.ttf";
  static const String Roboto_Medium = "assets/fonts/Roboto_Medium.ttf";
  static const String Roboto_MediumItalic = "assets/fonts/Roboto_MediumItalic.ttf";
  static const String Roboto_Regular = "assets/fonts/Roboto_Regular.ttf";
  static const String Roboto_Thin = "assets/fonts/Roboto_Thin.ttf";
  static const String Roboto_ThinItalic = "assets/fonts/Roboto_ThinItalic.ttf";
  static const String CustomIcons = "assets/icons/CustomIcons.ttf";
  static const String logo = "assets/images/logo.png";
  static const String splash = "assets/images/splash.png";
  static const String en = "assets/locale/en.json";
}
